### PR TITLE
Adding quality phase

### PR DESCRIPTION
**Pull request by nelsonjr**

### CODE REVIEW

**Comment by nelsonjr** [comment]
@delivery approve

**Comment by jjdelivery** [comment]
Failed to approve change: a97fdd2f-e861-463d-9ed7-02a76d1d74ba
  Change must pass verify before approving. @nelsonjr

**Comment by jjdelivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by nelsonjr** [comment]
@delivery approve

**Comment by jjdelivery** [comment]
Change: a97fdd2f-e861-463d-9ed7-02a76d1d74ba approved by: @nelsonjr

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
