### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by nelsonjr**

### CODE REVIEW

**Comment by jjdelivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jjasghar** [comment]
@delivery approve

**Comment by jjdelivery** [comment]
Change: 6a214cbb-4ea8-45d8-8e06-ef113b739f29 approved by: @jjasghar

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjasghar** [comment]
@delivery deliver

**Comment by jjdelivery** [comment]
Change: 6a214cbb-4ea8-45d8-8e06-ef113b739f29 delivered by: @jjasghar

**Pull request merged**
