### PR TITLE
Revert to simple app

### PR DESCRIPTION
**Pull request by nelsonjr**

### CODE REVIEW

**Comment by jjdelivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jjasghar** [comment]
@delivery approve

**Comment by jjdelivery** [comment]
Change: b94e4eef-2177-4243-bfbd-c8783940e5a9 approved by: @jjasghar

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
