### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by jjasghar**

### CODE REVIEW

**Comment by jjdelivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jjasghar** [comment]
@delivery approve

**Comment by jjdelivery** [comment]
Change: d705fc50-f09f-41ee-a5a2-6b61b283f229 approved by: @jjasghar

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
