### PR TITLE
removed some settings

### PR DESCRIPTION
**Pull request by jjasghar**

### CODE REVIEW

**Comment by jjdelivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jjasghar** [comment]
@delivery approve

**Comment by jjdelivery** [comment]
Change: 6b1e3555-a44f-4947-b37e-5f3d20730ee0 approved by: @jjasghar

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjasghar** [comment]
@delivery deliver

**Comment by jjdelivery** [comment]
Change: 6b1e3555-a44f-4947-b37e-5f3d20730ee0 delivered by: @jjasghar

**Pull request merged**
