### PR TITLE
image fix

### PR DESCRIPTION
**Pull request by nelsonjr**

### CODE REVIEW

**Comment by jjdelivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jjdelivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jjasghar** [comment]
@delivery deliver

**Comment by jjdelivery** [comment]
Change: ca8a788d-824d-41bd-b6e2-b9e8b35d7424 delivered by: @jjasghar

**Pull request merged**
